general:
  target_variable: "SalePrice"
  categorical_variables:
    - FireplaceQu
    - BsmtQual
    - BsmtCond
    - GarageQual
    - GarageCond
    - ExterQual
    - ExterCond
    - HeatingQC
    - PoolQC
    - KitchenQual
    - BsmtFinType1
    - BsmtFinType2
    - Functional
    - Fence
    - BsmtExposure
    - GarageFinish
    - LandSlope
    - LotShape
    - PavedDrive
    - Street
    - Alley
    - CentralAir
    - MSSubClass
    - OverallCond
    - YrSold
    - MoSold
    - MiscFeature
    - MSZoning
    - LandContour
    - Electrical
    - LotConfig
    - Neighborhood
    - Condition1
    - Condition2
    - BldgType
    - HouseStyle
    - RoofStyle
    - RoofMatl
    - GarageType
    - Exterior1st
    - Exterior2nd
    - Heating
    - Foundation
    - SaleType
    - SaleCondition
    - MasVnrType
preprocess:
  drop_cols:
    - Id
    - Utilities
    - LotShape
    - LotConfig
    - Condition2
    - BldgType
    - HouseStyle
    - BsmtQual
    - GarageYrBlt
    - GarageArea
    - MoSold
    - LandContour
    - RoofMatl
    - Exterior2nd
    - MasVnrArea
    - MasVnrType
    - FireplaceQu
    - Fence
    - MiscFeature
    - RoofStyle
    - Street
    - PoolQC
    - PoolArea
  fill_most_frequent:
    - MSZoning
    - Electrical
    - KitchenQual
    - Exterior1st
    - Exterior2nd
    - SaleType
  fill_custom:
    - value: "None"
      cols:
        - PoolQC
        - MiscFeature
        - Alley
        - Fence
        - FireplaceQu
        - GarageType
        - GarageFinish
        - GarageQual
        - GarageCond
        - BsmtQual
        - BsmtCond
        - BsmtExposure
        - BsmtFinType1
        - BsmtFinType2
        - MasVnrType
        - MSSubClass
    - value: "typ"
      cols:
        - Functional
    - value: 0
      cols:
        - GarageYrBlt
        - GarageArea
        - GarageCars
        - BsmtFinSF1
        - BsmtFinSF2
        - BsmtUnfSF
        - TotalBsmtSF
        - BsmtFullBath
        - BsmtHalfBath
        - MasVnrArea
  fill_median_groupby:
    - groupby_cols:
        - Neighborhood
      cols:
        - LotFrontage
  type_str_cols:

transform:
  log_cols:
  log1p_cols:
  boxcox1p_cols:
    - PoolArea
    - MiscVal
    - LowQualFinSF
    - 3SsnPorch
    - EnclosedPorch
    - KitchenAbvGr
    - BsmtFinSF2
    - ScreenPorch
    - BsmtHalfBath
    - LotArea
    - OpenPorchSF
    - MasVnrArea
    - WoodDeckSF
    - TotalSF
    - BsmtFinSF1
    - GrLivArea
    - BsmtUnfSF
    - TotRmsAbvGrd
    - Fireplaces
    - LotFrontage
  onehot_cols:
    - BsmtCond
    - GarageQual
    - GarageCond
    - ExterQual
    - ExterCond
    - HeatingQC
    - KitchenQual
    - BsmtFinType1
    - BsmtFinType2
    - Functional
    - BsmtExposure
    - GarageFinish
    - LandSlope
    - PavedDrive
    - Alley
    - CentralAir
    - MSSubClass
    - OverallCond
    - YrSold
    - MSZoning
    - Electrical
    - Neighborhood
    - Condition1
    - GarageType
    - Exterior1st
    - Heating
    - Foundation
    - SaleType
    - SaleCondition
  targetencode_cols:
  log_target: True
