name: ml
channels:
- defaults
- conda-forge
dependencies:
- python=3.7
- pandas=0.25.3
- numpy=1.17.4
- matplotlib=3.1.1
- seaborn=0.9.0
- pymssql=2.1.4
- pyarrow=0.13.0
- feather-format=0.4.0
- scikit-learn=0.21.2
- scikit-plot=0.3.7
- pyyaml=5.1.2
- eli5=0.10.1
- pylint=2.4.4
- tqdm=4.41.1
- pip
- pip:
  - ipython==7.10.1
  - lightgbm==2.3.1
  - xgboost==0.90